config/routes.rb
Rails.application.routes.draw do
  resources :rooms
  resources :users

  root 'home#index'

end

app/models/room.rb
class Room < ActiveRecord::Base
	def complete_name
		"#{title}, #{location}"
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	EMAIL_REGEXP = /\A[^@\s]+@([^@\s]+\.)+[^@\W]+\z/

	validates_presence_of :email, :full_name, :location, :password
	validates_confirmation_of :password
	validates_length_of :bio, minimun: 30, allow_blank: false
	validates_uniqueness_of :email

	validate do
		errors.add(:email, :invalid) unless email.match(EMAIL_REGEXP)
	end
end	

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@rooms = Room.take(3)
	end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:title, :location, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to @user,
				notice: 'Cadastro realizado com sucesso'
		else
			render action: :new
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			redirect_to @user,
				notice: 'Cadastro atualizado com sucesso'
		else
			render action: :edit
		end
	end

	private

	def user_params
		params.
			require(:user).
			permit(:email, :full_name, :location, :password, :password_confirmation, :bio)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def error_tag(model,attribute)
		if model.errors.has_key? attribute
			content_tag(
				:div,
				model.errors[attribute].first,
				class: 'error_message'
			)
		end
	end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/home/index.html.erb
<h1>Quartos recém postados</h1>
<ul>
	<% @rooms.each do |room| %>
	<li>
		<%= link_to room.complete_name, room %>
	</li>
	<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Colchonet</title>
  <link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
	<div id="header-wrap">
		<h1><%= link_to "Colcho.net", root_path %></h1>
		<nav>
			<ul>
				<li><%= link_to "Quartos", rooms_path%></li>
				<li><%= link_to "Cadastro", new_user_path%></li>
			</ul>
		</nav>
	</div>
</header>
<div id="content">
	<% if notice.present? %>
		<p id="notice"><%= notice %></p>
	<% end %>
	<% if alert.present? %>
		<p id="alert"><%= alert %></p>
	<% end %>

<%= yield %>

</div>
</body>
</html>

app/views/rooms/_form.html.erb
<%= form_for(@room) do |f| %>
 
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form' %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<h1>Listing Rooms</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Location</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.title %></td>
        <td><%= room.location %></td>
        <td><%= room.description %></td>
        <td><%= link_to 'Show', room %></td>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_room_path %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form' %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @room.title %>
</p>

<p>
  <strong>Location:</strong>
  <%= @room.location %>
</p>

<p>
  <strong>Description:</strong>
  <%= @room.description %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
<div id="error_explanation">
	<h2>Infelizmente, não foi possível completar a ação, pois o formulário possui os seguintes erros:</h2>
	<ul>
	<% @user.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
</div>
<% end %>


<%= form_for @user do |f| %>
	<p>
		<%= f.label :full_name %><br>
		<%= f.text_field :full_name %>
		<%= error_tag @user, :full_name %>
	</p>
	<p>
		<%= f.label :email %><br>
		<%= f.text_field :email %>
		<%= error_tag @user, :email %>
	</p>
	<p>
		<%= f.label :password %><br>
		<%= f.password_field :password %>
		<%= error_tag @user, :password %>
	</p>
	<p>
		<%= f.label :password_confirmation %><br>
		<%= f.password_field :password_confirmation %>
		<%= error_tag @user, :password_confirmation %>
	</p>
	<p>
		<%= f.label :location %><br>
		<%= f.text_field :location %>
		<%= error_tag @user, :location %>
	</p>
	<p>
		<%= f.label :bio %><br>
		<%= f.text_area :bio %>
		<%= error_tag @user, :bio %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/users/edit.erb
<h1>Editar Perfil</h1>

<%= render 'form' %>

<%= link_to "Voltar ao perfil", @user %>

app/views/users/new.html.erb
<h1>Cadastro</h1>

<%= render 'form' %>

<%= link_to "Voltar", root_path %>

app/views/users/show.html.erb
<h1>Perfil: <%= @user.full_name %></h1>

<ul>
	<li>Localização: <%= @user.location%></li>
	<li>Bio: <%= @user.bio %></li>
</ul>

<%= link_to "Editar Perfil", edit_user_path(@user) %>